name: cicd

on:
  push:
    branches: 
      - master

jobs:
  upload-schema:
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      SERVICE_1_URL: ${{ secrets.SERVICE_1_URL }}
      SERVICE_2_URL: ${{ secrets.SERVICE_2_URL }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.8.1 | sh

          # Add Rover to the $GITHUB_PATH so it can be used in another step
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      # only run this command with the `--background` flag if you have the Apollo Studio GitHub integration enabled on your repository
      - 
        name: Upload schema
        run: |
          rover subgraph publish prl-supergraph@current \
            --schema "./src/graphql/subgraph_1.graphql" \
            --name subgraph_1  \
            --routing-url "$SERVICE_1_URL"
          rover subgraph publish prl-supergraph@current \
            --schema "./src/graphql/subgraph_2.graphql" \
            --name subgraph_2  \
            --routing-url "$SERVICE_2_URL"
        

